version: '3'
services:
  test-web-app:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgresql-db
    depends_on:
      - postgresql-db
  postgresql-db:
    image: 'postgres:16.3-alpine3.20'
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
      PGDATA: '/var/lib/postgresql/data/pgdata'
